### ISSUE TITLE
No module named 'triqs.applications'

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/hubbardI#13] opened 2020-12-25 09:50 UTC
Dear all
Hi
I want use hubbardI method using triqs3.0.0 code. But when I want to run "python ce_gamma.py" from triqs webpage, I have following error:
`    from triqs.applications.impurity_solvers.hubbard_I.hubbard_solver import Solver
ModuleNotFoundError: No module named 'triqs.applications'`
Can you please help me to solve this error?
noticable that I installed triqs and hubbardI package without any errors. I should add some lines similar to triqs.install in my bashrs? if yes, what?
Thanks a lot
Sincerely yours
Reyhaneh

**Comment by Wentzell** [comment] 2021-01-04 15:37
Dear @Reyhanehe,

From you post it is not clear which example you are trying to run and where this is available on the website.
Please provide additional information.

Best

Nils

**Comment by Wentzell** [comment] 2021-01-04 15:46
This seems to be a duplicate of https://github.com/TRIQS/dft_tools/issues/156
Please **do not** post duplicate issues!
I am closing this.

**Closed as completed by Wentzell** 2021-01-04 15:46 UTC
